name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o build/ -v ./...
      
    - name: Copy Config
      run: cp ./config.json ./build/
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ./build
